### ISSUE TITLE
Add Longest Palindromic Substring Solution

### ISSUE THREAD

**Issue by Ariyaman** [mishra10008/HacktoberFest2021#17]
## Description
Add Longest Palindromic Substring Solution in Cpp.

**Comment by Ariyaman** [comment]
@mishra10008 Please assign this issue to me.

**Comment by sparsh0602** [comment]
I wanted to contribute in hactoberfest2021.
Please assign me this task.

I do alot of problem solving and also 3 star coder at codechef.
I will be able to do this.

**Comment by mishra10008** [comment]
ok
