### ISSUE TITLE
Valid Parentheses Solution (LeetCode)

### ISSUE THREAD

**Issue by RaunakGN2001** [mishra10008/HacktoberFest2021#18]
## Description
Add Valid Parentheses Solution cpp
## Link for the question
https://leetcode.com/problems/valid-parentheses/

**Comment by RaunakGN2001** [comment]
@mishra10008 kindly can you assign this issue to me?

**Comment by sparsh0602** [comment]
I wanted to contribute in hactoberfest2021.
Please assign me this task.

I do alot of problem solving and also 3 star coder at codechef.
I will be able to do this/

**Comment by snehashukkla** [comment]
I can solve this issue efficiently in C++,please assign it to me

**Comment by mishra10008** [comment]
Yeah go ahead geeks do it.
