### ISSUE TITLE
Request for permission to add 6 Codeforces Problems

### ISSUE THREAD

**Issue by jineshparakh** [mishra10008/HacktoberFest2021#51]
Hey!
I want to contribute to this repo by adding my solutions to the first 6 problems of Codeforces Round 744.
Can you please assign this to me?

**Comment by mishra10008** [comment]
yeah go ahead

**Comment by jineshparakh** [comment]
Sure!
Have added my solutions to 5 problems as 1 other was already present in the repo.
Please do review my pull request #94 and merge it!
Thanks!
